apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
  namespace: saleor
  labels:
    app: saleor
    component: exporter
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: saleor
      component: exporter
  template:
    metadata:
      labels:
        app: saleor
        component: exporter
    spec:
      containers:
        - name: exporter
          image: ovalmoney/celery-exporter:latest
          imagePullPolicy: Always
          ports:
            - name: exporter
              protocol: TCP
              containerPort: 9540
          args:
            - --broker-url=redis://redis.redis:6379/
