apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: saleor
  labels:
    app: saleor
    component: exporter
spec:
  type: ClusterIP
  selector:
    app: saleor
    component: exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9540
    targetPort: 9540
