apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: saleor
  labels:
    app: saleor
    component: worker
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: saleor
      component: worker
  template:
    metadata:
      labels:
        app: saleor
        component: worker
    spec:
      containers:
        - name: celery
          image: ariellahiany/saleor:latest
          imagePullPolicy: Always
          # todo: need to give password and username for Redis.
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django
                  key: DEBUG
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: django
                  key: CELERY_BROKER_URL
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          args: ["celery", "-A", "saleor", "--app=saleor.celery:app", "worker", "--loglevel=info"]
