apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: celery
  namespace: saleor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery
  maxReplicas: 3
  minReplicas: 1
