apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery
  namespace: saleor
  labels:
    app: saleor
    component: worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
