apiVersion: v1
kind: ConfigMap
metadata:
  name: django
  namespace: saleor
data:
  # Debug. By default should be set to "False".
  DEBUG: "False"

  # A list of strings representing host, or domain names of client applications.
  ALLOWED_HOSTS: 10.0.0.10,django,10.152.183.80

  # A list of strings representing host, or domain names of client applications that use Saleor as a backend.
  ALLOWED_CLIENT_HOSTS: 10.0.0.10,localhost,127.0.0.1

  # Default broker URL.
  CELERY_BROKER_URL: redis://redis.redis:6379/

  # todo: maybe need to change that, and give the dashboard ClusterIP with hostAliases.
  # Default Saleor Dashboard URL.
  DASHBOARD_URL: http://10.0.0.10:30090/

#  # Default Saleor Storefront URL.
#  STOREFRONT_URL: http://10.0.0.10:30030/
