apiVersion: v1
kind: ConfigMap
metadata:
  name: django
  namespace: saleor
data:
  # Debug. By default should be set to "False".
  DEBUG: "False"

  # todo: need to understand how to change that with Ansible for full deployment.
  # A list of strings representing host, or domain names of client applications.
  ALLOWED_CLIENT_HOSTS: "10.0.0.10"
