apiVersion: v1
kind: Secret
metadata:
  name: django
  namespace: saleor
type: Opaque
stringData:
  # Django secret key. Uses for creation of hashes.
  SECRET_KEY: 7uh#)e^@5k@ip!b8)7!(gfh^k%g(3fc^oeys0!l=09!5fuggxb
