apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: saleor
  labels:
    app: saleor
    component: server
spec:
  type: NodePort
  selector:
    app: saleor
    component: server
  ports:
    - name: django
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
