apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: saleor
  labels:
    app: saleor
    component: server
spec:
  type: ClusterIP
  clusterIP: 10.152.183.80
  selector:
    app: saleor
    component: server
  ports:
    - name: django
      protocol: TCP
      port: 80
      targetPort: 8000
