apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: beat
  namespace: saleor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beat
  maxReplicas: 3
  minReplicas: 1
