- name: Apply Saleor namespace manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/resources/manifests/namespaces/saleor.yaml

- name: Apply Beat schedulers media volume manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/saleor/manifests/beat/volume.yaml

- name: Apply Postgres database secret manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/resources/manifests/secrets/postgres.yaml

- name: Apply Beat schedulers deployment manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/saleor/manifests/beat/deployment.yaml
